### ISSUE TITLE
Missing qtypes.h file when building

### ISSUE THREAD

**Issue by Rbel12b** [valaczka/callofsuli#4]
I'm trying to build the project in wsl. But I ran into an issue: when executing the command `make` I get the following output:

> make[1]: Entering directory '/home/abel/callofsuli/build/client/src'
...
g++ -c -pipe -O2 -std=gnu++2a -Wall -Wextra -D_REENTRANT -fPIC -DQDEFERRED_USED -DCLIENT_UTILS -DQOLM_STATIC -DQATERIAL_STATIC -DQS_HAS_JSON -DQSERIALIZER_INCLUDED -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_CHARTS_LIB -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_PDF_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -I../../../client/src -I. -I../../../lib/callofsuli-core -I../../../lib/QDeferred/src -I../../../lib/QDeferred/src -I../../../lib/QDeferred/src -I../../../lib/QJsonWebToken/src -I../../../lib/QOlm/src -I../../../lib/QOlm/include -I../../../lib/Qaterial/src -I../../../lib/tiled/src -I../../../lib/tiled/src/libtiled -I../../../lib/tiled/src/libtiledquick -I../../../lib/SCodes/src -I../../../lib/SCodes/src/zxing-cpp/core/src -I/home/abel/callofsuli/lib/SCodes/src/zxing-cpp/thirdparty/stb/ -I../../../lib/qml-box2d -I../../../lib/qml-box2d/Box2D -I../../../lib/CuteLogger/include -I../../../lib/SortFilterProxyModel -I../../../lib/QtXlsxWriter/src/xlsx -I../../../lib/QSingleInstance/QSingleInstance -I../../../lib/qsyncable -I../../../lib/miniaudio -I../../../lib/tar_to_stream -I../../../lib/csv-parser/single_include -I../../../lib/stb -I../../../lib/QSerializer -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt6/QtQuick -I/usr/include/x86_64-linux-gnu/qt6/QtCharts -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt6/QtSvg -I/usr/include/x86_64-linux-gnu/qt6/QtGui/6.2.4 -I/usr/include/x86_64-linux-gnu/qt6/QtGui/6.2.4/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt6/QtPdf -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt6/QtQml -I/usr/include/x86_64-linux-gnu/qt6/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore/6.2.4 -I/usr/include/x86_64-linux-gnu/qt6/QtCore/6.2.4/QtCore -I/usr/include/x86_64-linux-gnu/qt6/QtCore5Compat -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -o actionrpggame.o ../../../client/src/actionrpggame.cpp
In file included from ../../../client/src/isometricobject.h:32,
                 from ../../../client/src/isometricbullet.h:30,
                 from ../../../client/src/tiledweapon.h:32,
                 from ../../../client/src/rpgarmory.h:30,
                 from ../../../client/src/rpgenemyiface.h:31,
                 from ../../../client/src/rpggame.h:32,
                 from ../../../client/src/actionrpggame.h:33,
                 from ../../../client/src/actionrpggame.cpp:27:
../../../client/src/isometricobjectiface.h:31:10: fatal error: qtypes.h: No such file or directory
   31 | #include "qtypes.h"
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:7191: actionrpggame.o] Error 1
../../../client/src/grade.cpp: In member function ‘Grade* GradingConfig::grade(const qreal&) const’:
../../../client/src/grade.cpp:195:47: error: ‘const class QHash<Grade*, std::pair<double, bool> >’ has no member named ‘asKeyValueRange’
  195 |         for (auto [grade, value] : m_gradeMap.asKeyValueRange()) {
      |                                               ^~~~~~~~~~~~~~~
make[1]: Leaving directory '/home/abel/callofsuli/build/client/src'
make[1]: *** [Makefile:8108: httpconnection.o] Error 1
make: *** [Makefile:180: sub-client-src-app-pro-make_first-ordered] Error 2

I cant find `qtypes.h` anywhere in the repository , and haven't found any library that contains this file.

I didn't change any files just ran these commands
```
git clone --recurse-submodules https://github.com/valaczka/callofsuli.git
cd callofsuli
mkdir build && cd build
qmake ../client.pro
make qmake_all
make
```
The last step results in the error above.

Am I missing a Qt module, or there is just something wrog with my enviroment?

**Comment by valaczka** [comment]
Please upgrade your Qt to version 6.7

**Comment by Rbel12b** [comment]
I upgraded my Qt and now it compiles without errors.
